title: nunogand
description: Apontamentos e recortes dispersos; coisas portanto...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nunogand.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    nunogand
author-image:   logo_main.png
author-job:     Já fiz muitas coisas...
author-email:   nunogand@gmail.com # Add your email for contant form.
author-twitter: nunogand # Add your twitter account
about-author:   Apontamentos e recortes dispersos; coisas portanto...

# Social settings
social-twitter:   nunogand
social-facebook:
social-github:    nunogand
social-pinterest: 
social-instagram: 
social-youtube: nunogand
social-vk:   
social-linkedin:

# Newsletter
# mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: UA-109060453-1 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  
timezone: Europe/Lisbon
locale: pt-pt
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
enable_coderay: false
