[build]
  command = "jekyll build -I"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

# REDIRECT and HEADERS examples.
# Uncomment to use. Directives in this file will ALWAYS override any identical
# directives present in either _redirects and _headers files, and also any
# settings added in Netlify's admin interface.

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# PER-DEPLOY.

# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

# Redirect rule example

#[[redirects]]
#  from = "/*"
#  to = "/blog/:splat"

# The default HTTP status code is always 301, but you can define a different
# one e.g. status = 302

# Headers rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

# netlify.toml

[[headers]]
  # Set the default header to the one we want for documents
  for = "/*"
    [headers.values]
    #cache-control = "public,max-age=60"
    cache-control = '''
 	 max-age=0,
 	 no-cache,
	 no-store,
	 must-revalidate''' 
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Accept-CH = "Downlink,RTT,Device-Memory,Save-Data,DPR,Width"
    
    Content-Security-Policy-Report-Only = '''
    default-src 'none'; 
    form-action 'none'; 
    frame-ancestors 'none'; 
    report-uri https://e1dc81c90a316052f52367a36438f250.report-uri.com/r/d/csp/reportOnly'''

#[[headers]]
#  # Override cache duration for assets with periods in the filename (i.e. static assets)
#  for = "/*.*"
#    [headers.values]
#    cache-control = "public,max-age=360000"

#[[headers]]
#   Define which paths this specific [[headers]] block will cover.
#  for = "/*"
#
#  [headers.values]
#    X-Frame-Options = "DENY"
#    X-XSS-Protection = "1; mode=block"
#    #Content-Security-Policy = "default-src https: unsafe-inline" 
#    Content-Security-Policy= "frame-ancestors 'none'"
#	 script-src 'self' www.google-analytics.com"
#	 
#    X-Content-Type-Options = "nosniff"

#    cache-control = '''
# 	  max-age=0,
# 	  no-cache,
#	  no-store,
#	  must-revalidate'''   

[build.processing]
  skip_processing = true
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
  
[[redirects]]
  from = "https://nunogand.netlify.app"
  to = "https://nunogand.com"
  status = 301
  force = true

# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/
